#!/usr/bin/env sh
git commit -am "autopush to origin and upstream-fork from $PWD/push"
echo Pushing to upstream-fork main : git@github.com:hobson/prishasatwani-chemformer
git push upstream-fork main
echo Pushing to origin main : git@github.com:CoreThink-AI/prishasatwani-chemformer
git push -u origin main
